image: composer/composer:latest

pipelines:
  default:
  - step:
      caches:
        - composer
      script:
        - composer global require phploc/phploc squizlabs/php_codesniffer phpmd/phpmd phpmetrics/phpmetrics
        - /composer/vendor/bin/phploc .
        - /composer/vendor/bin/phpmd . text cleancode,design,codesize,naming,unusedcode --ignore-violations-on-exit
        - /composer/vendor/bin/phpmetrics --exclude=vendor,tests --extensions=php .
        - /composer/vendor/bin/phpcs --extensions=php --standard=PSR2 .

definitions:
  caches:
    composer: /composer
