version: "3.6"
services:
    web:
        environment:
            - EXTENSION_KEY=save
            - PACKAGE_NAME=t3/save

            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=password
            - TYPO3_INSTALL_SITE_NAME=EXT:save Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/save
              consistency: cached
            - v9-data:/var/www/html/v9
            - v10-data:/var/www/html/v10
            - v11-data:/var/www/html/v11
volumes:
    v9-data:
        name: "${DDEV_SITENAME}-v9-data"
    v10-data:
        name: "${DDEV_SITENAME}-v10-data"
    v11-data:
        name: "${DDEV_SITENAME}-v11-data"
